name: frigoligo
description: Your articles with you
publish_to: "none"

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 3.0.0+42

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # dev & tooling
  equatable: 2.0.7
  flutter_riverpod: 3.0.0
  freezed_annotation: 3.1.0
  get_it: 9.2.0
  go_router: 17.0.0
  intl: any
  l10n_esperanto: 2.0.13
  logging: 1.3.0
  path_provider: 2.1.5
  path_provider_foundation: any
  riverpod_annotation: 3.0.0
  sqlite3: any

  # UI
  adaptive_dialog: 2.4.2
  any_image_view: 1.6.0
  cadanse: 1.6.1
  flutter_form_builder: 10.0.1
  flutter_widget_from_html: 0.17.0
  google_fonts: 6.2.1
  settings_ui: 2.0.2
  webview_flutter: 4.13.0
  webview_flutter_android: any
  webview_flutter_wkwebview: any

  # networking & API
  http: 1.4.0
  json_annotation: 4.9.0

  # data management
  drift: 2.28.1
  drift_flutter: 0.2.6
  shared_preferences: 2.5.3
  shared_preference_app_group: 1.1.1

  # platform integration
  app_links: 6.4.0
  background_fetch: 1.3.8
  device_info_plus: 12.3.0
  language_info_plus: 1.1.0
  neat_periodic_task: 2.0.1
  package_info_plus: 9.0.0
  universal_platform: 1.1.0
  url_launcher: 6.3.1
  share_plus: 12.0.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

  # lints
  custom_lint: 0.8.0
  flutter_lints: 6.0.0
  riverpod_lint: 3.0.0

  # code generation
  build_runner: any
  drift_dev: 2.28.2
  freezed: 3.2.3
  json_serializable: 6.11.1
  riverpod_generator: 3.0.0

  # automated testing
  emulators: 0.7.0
  mocktail: ^1.0.4
  test: ^1.25.8

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/article.template.html
    - assets/google_fonts/
    - assets/sample-articles.json
    - assets/www/scripts/
    - assets/www/styles/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
