name: frigoligo
description: Your articles with you
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.2.0+38

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # dev & tooling
  flutter_riverpod: 2.6.1
  flutter_svg: 2.0.16
  freezed_annotation: 2.4.4
  go_router: 14.6.2
  intl: any
  l10n_esperanto: 2.0.12
  logging: 1.3.0
  path_provider: 2.1.5
  riverpod_annotation: 2.6.1
  sqlite3: any

  # UI
  adaptive_dialog: 2.3.0
  cadanse: 1.3.1
  cupertino_icons: 1.0.8
  flutter_form_builder: 9.5.0
  flutter_widget_from_html_core: 0.15.2
  fwfh_cached_network_image: 0.14.3
  fwfh_url_launcher: 0.9.1
  google_fonts: 6.2.1
  settings_ui: 2.0.2

  # networking & API
  cached_network_image: 3.4.1
  http: 1.2.2
  json_annotation: 4.9.0

  # data management
  drift: 2.22.1
  drift_flutter: 0.2.3
  shared_preferences: 2.3.3
  shared_preference_app_group: 1.1.1

  # platform integration
  app_links: 6.3.3
  background_fetch: 1.3.7
  device_info_plus: 11.2.0
  neat_periodic_task: 2.0.1
  package_info_plus: 8.1.2
  universal_platform: 1.1.0
  url_launcher: 6.3.1
  share_plus: 10.1.3

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

  # lints
  custom_lint: 0.7.0
  flutter_lints: 5.0.0
  riverpod_lint: 2.6.3

  # code generation
  build_runner: any
  drift_dev: 2.22.1
  freezed: 2.5.7
  json_serializable: 6.9.0
  riverpod_generator: 2.6.3

  # automated testing
  emulators: 0.6.1
  test: ^1.25.8

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/google_fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
