blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussions
    url: https://github.com/casimir/frigoligo/discussions
    about: For general questions and discussions.
  - name: ğŸŒ Matrix
    url: https://matrix.to/#/#frigoligo:one.ems.host
    about: For live general questions and discussions.
